name: "Setup & Test"
description: "Setup node and run all tests"
runs:
  using: "composite"
  
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "18"

    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: Run tests
      run: npm run test:all
      shell: bash
      env:
        INFURA_PROJECT_ID: ${{ inputs.infura_project_id }}
        TEST_OWNER_WORLD_TOKEN_ID: ${{ inputs.test_owner_world_token_id }}
        TEST_OWNER_WORLD_ADDRESS: ${{ inputs.test_owner_world_address }}

  inputs:
    infura_project_id:
      description: 'Infura project ID'
      required: true
    test_owner_world_token_id:
      description: 'Test owner world token ID'
      required: true
    test_owner_world_address:
      description: 'Test owner world address'
      required: true