name: "Setup & Test"
description: "Setup node and run all tests"
runs:
  using: "composite"
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "18"

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm run test:all
      env:
        INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
        TEST_OWNER_WORLD_TOKEN_ID: ${{ secrets.TEST_OWNER_WORLD_TOKEN_ID }}
        TEST_OWNER_WORLD_ADDRESS: ${{ secrets.TEST_OWNER_WORLD_ADDRESS }}
