name: Run Tests

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    environment: Test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:all
        env:
          INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
          HYCHAIN_JSON_RPC_URL: ${{ secrets.HYCHAIN_JSON_RPC_URL }}
          TEST_OWNER_WORLD_TOKEN_ID: ${{ secrets.TEST_OWNER_WORLD_TOKEN_ID }}
          TEST_OWNER_WORLD_ADDRESS: ${{ secrets.TEST_OWNER_WORLD_ADDRESS }}
          TEST_NODE_KEY_OWNER_ADDRESS: ${{ secrets.TEST_NODE_KEY_OWNER_ADDRESS }}
          TEST_NODE_ID_WITH_REWARDS: ${{ secrets.TEST_NODE_ID_WITH_REWARDS }}

      - name: "Upload Coverage"
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: KodiKraig/hytopia-steaks
