name: Test & Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Run tests
        uses: ./.github/actions/setup-test

      - name: Upload coverage reports to Codecov
        uses: ./.github/actions/upload-codecov

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
