name: Test & Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        uses: ./.github/actions/setup-test
        with:
          infura_project_id: ${{ secrets.INFURA_PROJECT_ID }}
          test_owner_world_token_id: ${{ secrets.TEST_OWNER_WORLD_TOKEN_ID }}
          test_owner_world_address: ${{ secrets.TEST_OWNER_WORLD_ADDRESS }}

      - name: Upload coverage reports to Codecov
        uses: ./.github/actions/upload-codecov
        with:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
